[package]
name = "termitarium"
version = "0.1.0"
authors = ["Ferran Pujol Camins <ferranpujolcamins@gmail.com>"]

[lib]
name = "termitarium_lib"
path = "src/lib.rs"

[[bin]]
name = "termitarium"
path = "src/main.rs"